development:
  adapter: postgresql
  encoding: unicode
  database: motels
  host: localhost
  username: "postgres" 
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: production
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  host: <%= ENV[‘DATABASE_HOST’] %>
  pool: 5