development:
  adapter: postgresql
  encoding: unicode
  database: phase-3-project
  host: localhost
  username: 'motels' 
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: production
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  host: <%= ENV[‘DATABASE_HOST’] %>
  pool: 5
